if (UNIX)
  set(HOME_DIR $ENV{HOME})
else()
  set(HOME_DIR $ENV{homedrive}$ENV{homepath})
endif()

set(WORKSPACE_DIR ${HOME_DIR}/workspace)
set(TP_DIR ${WORKSPACE_DIR}/third-party)
set(PYBIND11_DIR ${TP_DIR}/pybind11)
set(PROTOBUF_DIR ${TP_DIR}/protobuf)


function(add_pybind_subdirectory)
  set(ADD_PYBIND ON)
  if ($ENV{IS_PYBIND11_ADDED})
    if ($ENV{IS_PYBIND11_ADDED} STREQUAL "TRUE")
      set(ADD_PYBIND OFF)
    endif()
  endif()

  if(${ADD_PYBIND})
    add_subdirectory(${PYBIND11_DIR} ${PYBIND11_DIR}/build)
    set(ENV{IS_PYBIND11_ADDED} "TRUE")
  endif()
endfunction()
